-- 3-3
SELECT * FROM CUSTOMER;
-- 3-4
SELECT * FROM ACCOUNT;
-- 3-5
SELECT * FROM CUSTOMER;
-- 3-6
SELECT * FROM TRANSACTION;
-- 3-7
SELECT C_NAME, C_ID FROM CUSTOMER;
-- 3-8
SELECT ACC_TYPE, ACC_NAME FROM ACCOUNT;
-- 3-9
SELECT DISTINCT ACC_TYPE, ACC_NAME FROM ACCOUNT;
-- 3-10
SELECT * FROM ACCOUNT WHERE ACC_BALANCE > 1000000 AND ACC_NAME = '자유저축예금';
-- 3-11
SELECT * FROM CUSTOMER WHERE C_ADDR LIKE '경기도%';
-- 3-12
SELECT * FROM CUSTOMER WHERE C_TYPE = 2;
-- 3-13
SELECT * FROM TRANSACTION WHERE TR_TYPE = 1;
-- 3-14
SELECT * FROM transaction WHERE TR_TYPE =2 ORDER BY TR_AMOUNT DESC;
-- 3-15
SELECT SUM(TR_AMOUNT) AS "입금총합", AVG(TR_AMOUNT) AS "입금평균" FROM TRANSACTION WHERE TR_TYPE=1;
-- 3-16
SELECT MAX(TR_AMOUNT) AS "큰금액", MIN(TR_AMOUNT) AS "작은 금액" FROM TRANSACTION WHERE TR_TYPE=2;
-- 3-17
SELECT * FROM ACCOUNT WHERE ACC_BALANCE > 1000000 AND ACC_NAME = '자유저축예금' ORDER BY ACC_BALANCE DESC;
-- 3-18
SELECT * FROM ACCOUNT WHERE ACC_NAME = '자유저축예금' ORDER BY ACC_BALANCE DESC FETCH FIRST 1 ROWS ONLY;
-- 3-19
SELECT * FROM TRANSACTION WHERE TR_TYPE = 1 OR TR_TYPE =2 ORDER BY TR_TYPE, TR_AMOUNT DESC;
-- 3-20
SELECT
COUNT(CASE WHEN TR_TYPE = 0 THEN 1 END) AS "조회 건수",
COUNT(CASE WHEN TR_TYPE = 1 THEN 1 END) AS "입금 건수",
COUNT(CASE WHEN TR_TYPE = 2 THEN 1 END) AS "출금 건수"
FROM TRANSACTION;
-- 3-21
SELECT TR_TYPE, CASE
WHEN TR_TYPE = 0 THEN '조회'
WHEN TR_TYPE = 1 THEN  '입금'
WHEN TR_TYPE = 2 THEN  '출금'
END AS "거래종류", TR_ACC, TR_AMOUNT FROM TRANSACTION;
-- 3-22
SELECT TR_TYPE, COUNT(TR_NO) FROM TRANSACTION
GROUP BY TR_TYPE;

SELECT TR_ACC, TR_TYPE, SUN(TR_AMOUNT) AS "합계"
FROM